### ISSUE TITLE
There is an issue if only one record in the tree

### ISSUE THREAD

**Issue by ozvaris** [richhaigh/btreenode#1]
Hi richhaigh,

thank you for your effort,

if items.length === 1, root return empty. Please check code blow .

Thanks.

const balanceTree = function (tree, items) {
   ...
    if (items.length === 1) {
      tree.add(items[0]);
      return;
    }

**Comment by richhaigh** [comment]
Thanks for reporting this. 

I have found n issue with the balance method which was causing the root node to be set to nil when only one time existing in the tree.

A fix has been added to check for a single item tree to the balance method
